@echo off
chcp 65001 >nul
title Laptop Setup Launcher

:: 检查是否管理员运行
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo Requesting administrator permission...
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath '%~f0' -Verb RunAs -WorkingDirectory '%~dp0'"
    exit /b
)

set "SourcePath=%~dp0."
set "TargetPath=C:\temp"
set "ScriptName=装软件.ps1"
set "ScriptPath=%TargetPath%\%ScriptName%"

echo Source: %SourcePath%
echo Target: %TargetPath%
echo.

if not exist "%TargetPath%" (
    echo Creating C:\temp ...
    mkdir "%TargetPath%"
)

set "SourcePath=%~dp0."
set "TargetPath=C:\temp"
set "ScriptName=装软件.ps1"
set "ScriptPath=%TargetPath%\%ScriptName%"

echo Configuring Microsoft Defender exclusions...

set "ESAFE_SOURCE=%~dp0亿赛通加密软件"

powershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKAHQAcgB5ACAAewAKACAAIAAgACAAJABwAGEAdABoAHMAIAA9ACAAQAAoAAoAIAAgACAAIAAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBQAGEAdABoAF0AOgA6AEcAZQB0AEYAdQBsAGwAUABhAHQAaAAoACQAZQBuAHYAOgBFAFMAQQBGAEUAXwBTAE8AVQBSAEMARQApAC4AVAByAGkAbQBFAG4AZAAoACcAXAAnACkACgAgACAAIAAgACAAIAAgACAAJwBDADoAXAB0AGUAbQBwAFwAv05bjRqQoFLGW2+P9k4nAAoAIAAgACAAIAAgACAAIAAgACcAQwA6AFwAUAByAG8AZwByAGEAbQAgAEYAaQBsAGUAcwBcAEUAcwBhAGYAZQBOAGUAdAAnAAoAIAAgACAAIAApACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAFUAbgBpAHEAdQBlAAoACgAgACAAIAAgACQAYwB1AHIAcgBlAG4AdAAgAD0AIABAACgAKABHAGUAdAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwACkALgBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACkAIAB8AAoAIAAgACAAIAAgACAAIAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAIAAkAF8ALgBUAHIAaQBtAEUAbgBkACgAJwBcACcAKQAgAH0ACgAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABwAGEAdABoACAAaQBuACAAJABwAGEAdABoAHMAKQAgAHsACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAGMAdQByAHIAZQBuAHQAIAAtAG4AbwB0AGMAbwBuAHQAYQBpAG4AcwAgACQAcABhAHQAaAApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEUAeABjAGwAdQBzAGkAbwBuAFAAYQB0AGgAIAAkAHAAYQB0AGgAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBBAGQAZABlAGQAIABEAGUAZgBlAG4AZABlAHIAIABlAHgAYwBsAHUAcwBpAG8AbgA6ACAAJABwAGEAdABoACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAZQBsAHMAZQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBBAGwAcgBlAGEAZAB5ACAAZQB4AGMAbAB1AGQAZQBkADoAIAAkAHAAYQB0AGgAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoACgAgACAAIAAgACQAZQBmAGYAZQBjAHQAaQB2AGUAIAA9ACAAQAAoACgARwBlAHQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwB0AG8AcAApAC4ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAApACAAfAAKACAAIAAgACAAIAAgACAAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfAC4AVAByAGkAbQBFAG4AZAAoACcAXAAnACkAIAB9AAoAIAAgACAAIAAkAG0AaQBzAHMAaQBuAGcAIAA9ACAAQAAoACQAcABhAHQAaABzACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAZQBmAGYAZQBjAHQAaQB2AGUAIAAtAG4AbwB0AGMAbwBuAHQAYQBpAG4AcwAgACQAXwAgAH0AKQAKAAoAIAAgACAAIABpAGYAIAAoACQAbQBpAHMAcwBpAG4AZwAuAEMAbwB1AG4AdAAgAC0AZwB0ACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAB0AGgAcgBvAHcAIAAiAEQAZQBmAGUAbgBkAGUAcgAgAGUAeABjAGwAdQBzAGkAbwBuAHMAIABuAG8AdAAgAGUAZgBmAGUAYwB0AGkAdgBlADoAIAAkACgAJABtAGkAcwBzAGkAbgBnACAALQBqAG8AaQBuACAAJwAsACAAJwApACIACgAgACAAIAAgAH0ACgAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcAQQBsAGwAIABEAGUAZgBlAG4AZABlAHIAIABlAHgAYwBsAHUAcwBpAG8AbgBzACAAYQByAGUAIABlAGYAZgBlAGMAdABpAHYAZQAuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAIAAgACAAIABlAHgAaQB0ACAAMAAKAH0ACgBjAGEAdABjAGgAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBFAHIAcgBvAHIAIAAiAEYAYQBpAGwAZQBkACAAdABvACAAYwBvAG4AZgBpAGcAdQByAGUAIABEAGUAZgBlAG4AZABlAHIAIABlAHgAYwBsAHUAcwBpAG8AbgBzADoAIAAkACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkAIgAKACAAIAAgACAAZQB4AGkAdAAgADEACgB9AA==

if errorlevel 1 (
    echo.
    echo Failed to configure Defender exclusions.
    pause
    exit /b 1
)

echo Defender exclusions configured successfully.
echo.

echo Copying files from "%SourcePath%" to "%TargetPath%" ...
robocopy "%SourcePath%" "%TargetPath%" /E /R:2 /W:2

if %errorlevel% GEQ 8 (
    echo.
    echo Copy failed.
    pause
    exit /b 1
)

echo.
echo Copy completed.

if not exist "%ScriptPath%" (
    echo.
    echo PowerShell script not found: %ScriptPath%
    pause
    exit /b 1
)

echo.
echo Starting PowerShell setup script...
echo.

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%ScriptPath%"

echo.
echo Setup script finished.
pause
